FROM oven/bun:1-alpine

WORKDIR /app

COPY package.json /app/

COPY /discord-bot/package.json /app/discord-bot/

RUN bun install --production

COPY discord-bot /app/discord-bot

RUN mkdir /app/modules

EXPOSE 8080

CMD [ "bun", "run", "start:discord-bot" ]